name: tests

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      SKIP: pytest-unit
    steps:
      - uses: neuroinformatics-unit/actions/lint@v2

  manifest:
    name: Check Manifest
    runs-on: ubuntu-latest
    steps:
      - uses: neuroinformatics-unit/actions/check_manifest@v2

  test:
    needs: [linting, manifest]
    name: ubuntu py3.11
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies for pyalsaaudio
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      - uses: neuroinformatics-unit/actions/test@v2
        with:
          python-version: "3.11"
